//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DcTransferFtpNew.GetDataAntarDC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataAntarDCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNoTglPBOperationCompleted;
        
        private System.Threading.SendOrPostCallback Cek_RekonOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_BpbDcOperationCompleted;
        
        private System.Threading.SendOrPostCallback del_npbOperationCompleted;
        
        private System.Threading.SendOrPostCallback ins_rekon_bpbdcOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::DcTransferFtpNew.Properties.Settings.Default.DcTransferFtpNew_GetDataAntarDC_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataAntarDCCompletedEventHandler GetDataAntarDCCompleted;
        
        /// <remarks/>
        public event GetNoTglPBCompletedEventHandler GetNoTglPBCompleted;
        
        /// <remarks/>
        public event Cek_RekonCompletedEventHandler Cek_RekonCompleted;
        
        /// <remarks/>
        public event Get_BpbDcCompletedEventHandler Get_BpbDcCompleted;
        
        /// <remarks/>
        public event del_npbCompletedEventHandler del_npbCompleted;
        
        /// <remarks/>
        public event ins_rekon_bpbdcCompletedEventHandler ins_rekon_bpbdcCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataAntarDC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDataAntarDC() {
            object[] results = this.Invoke("GetDataAntarDC", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAntarDCAsync() {
            this.GetDataAntarDCAsync(null);
        }
        
        /// <remarks/>
        public void GetDataAntarDCAsync(object userState) {
            if ((this.GetDataAntarDCOperationCompleted == null)) {
                this.GetDataAntarDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataAntarDCOperationCompleted);
            }
            this.InvokeAsync("GetDataAntarDC", new object[0], this.GetDataAntarDCOperationCompleted, userState);
        }
        
        private void OnGetDataAntarDCOperationCompleted(object arg) {
            if ((this.GetDataAntarDCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataAntarDCCompleted(this, new GetDataAntarDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNoTglPB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNoTglPB(string p_kodeDCAsal, string p_kodeDCTujuan) {
            object[] results = this.Invoke("GetNoTglPB", new object[] {
                        p_kodeDCAsal,
                        p_kodeDCTujuan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNoTglPBAsync(string p_kodeDCAsal, string p_kodeDCTujuan) {
            this.GetNoTglPBAsync(p_kodeDCAsal, p_kodeDCTujuan, null);
        }
        
        /// <remarks/>
        public void GetNoTglPBAsync(string p_kodeDCAsal, string p_kodeDCTujuan, object userState) {
            if ((this.GetNoTglPBOperationCompleted == null)) {
                this.GetNoTglPBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNoTglPBOperationCompleted);
            }
            this.InvokeAsync("GetNoTglPB", new object[] {
                        p_kodeDCAsal,
                        p_kodeDCTujuan}, this.GetNoTglPBOperationCompleted, userState);
        }
        
        private void OnGetNoTglPBOperationCompleted(object arg) {
            if ((this.GetNoTglPBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNoTglPBCompleted(this, new GetNoTglPBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cek_Rekon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Cek_Rekon(string p_dckirim, string p_dctujuan, int p_docno, System.DateTime p_tgl) {
            object[] results = this.Invoke("Cek_Rekon", new object[] {
                        p_dckirim,
                        p_dctujuan,
                        p_docno,
                        p_tgl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Cek_RekonAsync(string p_dckirim, string p_dctujuan, int p_docno, System.DateTime p_tgl) {
            this.Cek_RekonAsync(p_dckirim, p_dctujuan, p_docno, p_tgl, null);
        }
        
        /// <remarks/>
        public void Cek_RekonAsync(string p_dckirim, string p_dctujuan, int p_docno, System.DateTime p_tgl, object userState) {
            if ((this.Cek_RekonOperationCompleted == null)) {
                this.Cek_RekonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCek_RekonOperationCompleted);
            }
            this.InvokeAsync("Cek_Rekon", new object[] {
                        p_dckirim,
                        p_dctujuan,
                        p_docno,
                        p_tgl}, this.Cek_RekonOperationCompleted, userState);
        }
        
        private void OnCek_RekonOperationCompleted(object arg) {
            if ((this.Cek_RekonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cek_RekonCompleted(this, new Cek_RekonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_BpbDc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_BpbDc(string p_dckirim, string p_dctujuan, int p_docno, string p_tgl) {
            object[] results = this.Invoke("Get_BpbDc", new object[] {
                        p_dckirim,
                        p_dctujuan,
                        p_docno,
                        p_tgl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_BpbDcAsync(string p_dckirim, string p_dctujuan, int p_docno, string p_tgl) {
            this.Get_BpbDcAsync(p_dckirim, p_dctujuan, p_docno, p_tgl, null);
        }
        
        /// <remarks/>
        public void Get_BpbDcAsync(string p_dckirim, string p_dctujuan, int p_docno, string p_tgl, object userState) {
            if ((this.Get_BpbDcOperationCompleted == null)) {
                this.Get_BpbDcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_BpbDcOperationCompleted);
            }
            this.InvokeAsync("Get_BpbDc", new object[] {
                        p_dckirim,
                        p_dctujuan,
                        p_docno,
                        p_tgl}, this.Get_BpbDcOperationCompleted, userState);
        }
        
        private void OnGet_BpbDcOperationCompleted(object arg) {
            if ((this.Get_BpbDcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_BpbDcCompleted(this, new Get_BpbDcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/del_npb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string del_npb(string p_dckirim, string p_dctujuan, int p_docno, string p_tgl, bool p_isUpdate) {
            object[] results = this.Invoke("del_npb", new object[] {
                        p_dckirim,
                        p_dctujuan,
                        p_docno,
                        p_tgl,
                        p_isUpdate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void del_npbAsync(string p_dckirim, string p_dctujuan, int p_docno, string p_tgl, bool p_isUpdate) {
            this.del_npbAsync(p_dckirim, p_dctujuan, p_docno, p_tgl, p_isUpdate, null);
        }
        
        /// <remarks/>
        public void del_npbAsync(string p_dckirim, string p_dctujuan, int p_docno, string p_tgl, bool p_isUpdate, object userState) {
            if ((this.del_npbOperationCompleted == null)) {
                this.del_npbOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondel_npbOperationCompleted);
            }
            this.InvokeAsync("del_npb", new object[] {
                        p_dckirim,
                        p_dctujuan,
                        p_docno,
                        p_tgl,
                        p_isUpdate}, this.del_npbOperationCompleted, userState);
        }
        
        private void Ondel_npbOperationCompleted(object arg) {
            if ((this.del_npbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.del_npbCompleted(this, new del_npbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ins_rekon_bpbdc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ins_rekon_bpbdc(string p_type_trans, int p_hdrid, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] p_byte) {
            object[] results = this.Invoke("ins_rekon_bpbdc", new object[] {
                        p_type_trans,
                        p_hdrid,
                        p_byte});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ins_rekon_bpbdcAsync(string p_type_trans, int p_hdrid, byte[] p_byte) {
            this.ins_rekon_bpbdcAsync(p_type_trans, p_hdrid, p_byte, null);
        }
        
        /// <remarks/>
        public void ins_rekon_bpbdcAsync(string p_type_trans, int p_hdrid, byte[] p_byte, object userState) {
            if ((this.ins_rekon_bpbdcOperationCompleted == null)) {
                this.ins_rekon_bpbdcOperationCompleted = new System.Threading.SendOrPostCallback(this.Onins_rekon_bpbdcOperationCompleted);
            }
            this.InvokeAsync("ins_rekon_bpbdc", new object[] {
                        p_type_trans,
                        p_hdrid,
                        p_byte}, this.ins_rekon_bpbdcOperationCompleted, userState);
        }
        
        private void Onins_rekon_bpbdcOperationCompleted(object arg) {
            if ((this.ins_rekon_bpbdcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ins_rekon_bpbdcCompleted(this, new ins_rekon_bpbdcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataAntarDCCompletedEventHandler(object sender, GetDataAntarDCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataAntarDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataAntarDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetNoTglPBCompletedEventHandler(object sender, GetNoTglPBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNoTglPBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNoTglPBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Cek_RekonCompletedEventHandler(object sender, Cek_RekonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cek_RekonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cek_RekonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_BpbDcCompletedEventHandler(object sender, Get_BpbDcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_BpbDcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_BpbDcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void del_npbCompletedEventHandler(object sender, del_npbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class del_npbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal del_npbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ins_rekon_bpbdcCompletedEventHandler(object sender, ins_rekon_bpbdcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ins_rekon_bpbdcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ins_rekon_bpbdcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591